version: "3.9"
services:
  dashfolio:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      DASHFOLIO_DATA_DIR: /mnt/config/dashfolio
    volumes:
      - ./dashfolio-data:/mnt/config/dashfolio
    restart: unless-stopped
